HandSize 5 // do not change this value
StartingHandSize 3
CardsPerRound 1
StartingEnergy 3
RoundOverEnergy 2
FireTowers 1
IceTowers 1
TreeTowers 1
CauldronTowers 0
CannonTowers 1
PoisonTowers 0
SeagullTowers 1
BallistaTowers 0
LightningTowers 1
