name BallistaTowers
icon assets/sts/textures/icons/ballista_tower_icon.png
level 1
range 5.0
damage 2.0
cost 2
coolDown 1.75
default_target_option nearest
tower_target_options nearest first last most_health least_health end_line_parse