name CannonTower
icon assets/sts/textures/icons/cannon_tower_icon.png
level 1
damage 5.0
aoe 6.0
minRange 3.0
range 8.0
projectileSpeed 15.0
timeToFire 5
cost 3
default_target_option nearest
tower_target_options nearest first last most_health least_health end_line_parse