name FireTower
icon assets/sts/textures/icons/fire_tower_icon.png
level 1
range 3.5
damage 1.0
fireballSpeed 10.0
timeToFire 1.3
cost 1
default_target_option nearest
tower_target_options nearest first last most_health least_health end_line_parse