name IceTower
icon assets/sts/textures/icons/ice_tower_icon.png
level 1
range 2.0
maxSlimeToFreeze 1
damageOnBreakingFreeze 1.5
towerFreezeCountDown 3.0
freezeTime 0.5
chill_slow_down 0.65
cost 2
default_target_option nearest
tower_target_options nearest first last most_health least_health end_line_parse