name LightningTower
icon assets/sts/textures/icons/lightning_tower_icon.png
level 1
range 4.0
damage 1.5
cost 2
coolDown 2.0
chaining 3
default_target_option nearest
tower_target_options nearest end_line_parse
