name PoisonTower
icon assets/sts/textures/icons/poison_tower_icon.png
cost 1
level 1
damage 0.3
range 1.5
countDown 5.5
puffTime 0.5
puffScale 1.2
poisonEffectTime 1.0
poisonCloudTime 3.0
minPoisonHits 1
maxPoisonHits 9